#%RAML 1.0
title: HSSTIP API STUDENT
version: v1
baseUri: http://145.97.16.185/{version}

securitySchemes:

/students/all:
  get:
    description: List all students matching query criteria.
    responses:
      200:
        body:
          application/json:
            example:
              {
              "id": "5a146b0f5c0e8c2e30ec3a42",
              "sureName": "Hans",
              "middleName": "de",
              "lastName": "Gans",
              "email": "s123@student.hsleiden.nl",
              "password": "password123",
              "phoneNumber": "0612341234",
              }
      401:
        body:
          application/json:
            example:
              {
                "message" : "Unauthorized."
              }
      404:
        body:
          application/json:
            example:
              {
                "message": "Resource path not found"
              }


/students:
  post:
    description: Create a new Student
    responses:
      200:
        body:
          application/json:
            type: object
            properties:
              sureName: string
              middleName: string
              lastName: string
              email: string
              password: string
              phoneNumber: string
            example:
              {
              "sureName": "Hans",
              "middleName": "de",
              "lastName": "Gans",
              "email": "s123@student.hsleiden.nl",
              "password": "password123",
              "phoneNumber": "0612341234",
              }
      401:
        body:
          application/json:
            example:
              {
                 "message" : "Unauthorized."
              }
      404:
        body:
          application/json:
            example:
              {
                message": "Couldn't create a new Student"
              }


  put:
    description: Update a Student
    responses:
      200:
        body:
          application/json:
            type: object
            properties:
              id: string
              sureName: string
              middleName: string
              lastName: string
              email: string
              password: string
              phoneNumber: string
            example:
              {
              "id": "5a146b0f5c0e8c2e30ec3a42",
              "sureName": "Hans",
              "middleName": "de",
              "lastName": "Gans",
              "email": "s123@student.hsleiden.nl",
              "password": "password123",
              "phoneNumber": "0612341234",
              }
      401:
        body:
          application/json:
            example:
              {
                 "message" : "Unauthorized."
              }
      404:
        body:
          application/json:
            example:
              {
                message": "Couldn't update a student"
              }

  /{email}:
    get:
      description: Retrieve a specific student by email
      # queryParameters:
      #   email : string
      headers:
        key:
          displayName: key
          description: email
          type: string
        value:
          displayName: value
          description: email from student
          type: string
      responses:
        200:
          body:
            application/json:
              type: object
              properties:
                sureName: string
                middleName: string
                lastName: string
                email: string
                password: string
                phoneNumber: string
              example:
                {
                "sureName": "Hans",
                "middleName": "de",
                "lastName": "Gans",
                "email": "s123@student.hsleiden.nl",
                "password": "password123",
                "phoneNumber": "0612341234",
                }
        401:
          body:
            application/json:
              example:
                {
                   "message" : "Unauthorized."
                }
        404:
          body:
            application/json:
              example:
                {
                  message": "Couldn't update a student"
                }
